const INVALID_DATA_ERROR = 400;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const DEFAULT_ERROR = 500;

module.exports = {
  INVALID_DATA_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_ERROR,
  DEFAULT_ERROR,
};
